### ISSUE TITLE
Error in collectri example

### ISSUE THREAD

**Issue by pietrisko** [saezlab/CollecTRI#10]
Hello,

'organism' in `collectri` function does not accept strings, just numbers, as 9606L for human.

`OmnipathR::collectri(organism='human', genesymbols=TRUE, loops=TRUE)`

Also, what does it do 'loops' parameter? Thanks.

**Comment by PauBadiaM** [comment]
Hi @pietrisko,

Indeed, the raw function from `OmnipathR` does not accept strings, for that, please use the wrapper provided by decoupleR: `decoupleR::get_collectri`. Keep in mind that this function also deals with the AP1 and NFKB TF complexes which the one in `OmnipathR` does not.
The loops parameter means that when building the network, loops are allowed (an edge that connects a node to itself), so that a TF can be the target of itself.
Hope this is helpful!

**Comment by smuellerd** [comment]
Thanks for pointing this out @pietrisko! I corrected this in the example now.
