### ISSUE TITLE
Missing TF in mouse TRI network

### ISSUE THREAD

**Issue by thnbio** [saezlab/CollecTRI#20]
Hello,

I am using DecoupleR to analyze TF activity in mice looking at a set of DEGs for Ctrl vs KO post DeSeq2. When I loaded the mouse TRI network, I noticed that one of the TFs of interest is missing ("Stat1", see attached screenshot when looking into the "net" object)
<img width="296" alt="Screenshot 2024-07-02 at 1 01 56 PM" src="https://github.com/saezlab/CollecTRI/assets/143016066/f48d1fa2-02d4-4b46-8005-7c3e8a92af7b">

However, when I loaded the human TRI, STAT1 is there, and even though I can do a workaround by converting all of my DEGs into human symbols, I am wondering:
1) why "Stat1" is missing from mouse TRI 
2) If mouse Stat1 network is not available, is it appropriate to use convert my DEGs into human symbols then run ULM for TF activity? 

Many thanks!

**Comment by deeenes** [comment]
Hello @thnbio,

This is an interesting finding, and apologies for the late reply!

The reason is that OMA maps the [STAT1_HUMAN](https://omabrowser.org/oma/vps/13012415/) record to this [mouse TrEBML record](https://omabrowser.org/oma/vps/MOUSE27805/). I'm aware of a few similar cases, and I have to address this somehow because it indeed results loss of data when translating to mouse.

Meanwhile it is possible to fall back to the outdated NCBI HomoloGene:

```
library(OmnipathR)
library(magrittr)

ci <- collectri()
ci_mouse <-
  ci %>%
  orthology_translate_column(
    source_genesymbol,
	genesymbol,    
    resource = 'homologene',
    replace = TRUE
  ) %>%
  orthology_translate_column(
    target_genesymbol,
	genesymbol,    
    resource = 'homologene',
    replace = TRUE
  )
```

The same can be done with the UniProt IDs. If you try these, please update OmnipathR from our git repo:

```
library(remotes)
remotes::install_github('saezlab/OmnipathR')
```
