### ISSUE TITLE
High activity but no expression of a TF

### ISSUE THREAD

**Issue by BastiDucreux** [saezlab/CollecTRI#8]
Hi,

I am reading the collecTRI vignette with great interest, but I have an interrogation regarding biological significance of a result presented in the documentation.

![](https://saezlab.github.io/decoupleR/articles/tf_sc_files/figure-html/projected_acts-1.png)

There seems to be no expression of PAX5 is all samples except 2, whereas in the upper cluster the activity of PAX5 is infered to be increased. I cannot figure out how this result would be biologically true if the TF is not expressed.
Maybe the regulons of PAX5 showed variation fo expression, but not because of PAX5 binding (maybe other members of PAX family).

Thus I have reservations about the meaning of "TF activity" in that case, maybe you could enlighten me on how to interpret such particular cases ? Thanks.

**Comment by PauBadiaM** [comment]
Hi @BastiDucreux ,

Thanks for the interest in collecTRI. Regarding your question, transcripts of a TF do not always correlate with the activity of said regulator. This is because for a TF transcript to become an active protein, it first needs to exit the nucleus, get translated, potentially get some postranslational modifications, reenter the nucleus, cooperate with other TFs and depending on the chromatin state it will trigger or inhibit transcription of other genes. As you can see, just assuming that that transcript is going to do all this is a huge jump. Additionally, in single-cell we have a lot of drop out effects, so this leads to a bigger mismatch between transcript abundance and protein activity. Therefore, looking at the targets of said TF is way more informative (in the end, what you are measuring with trasncriptomics its this, the downstream effects of an active TF). Of course that some predicted TFs might be false positives, but here we purposely choose PAX5 since it is a known TF that maintains the B cell lineage. One way to mitigate these could be to check if your active TFs is at least present at the protein level in your tissue of interest, which can be done by querying the human protein atlas database for example (you can retrieve it using `decoupleR::get_resource('HPA_tissue')` for example. Hope this is helpful!

**Comment by BastiDucreux** [comment]
Really helpful ! Thank you very much for providing these clarifications
